# Generated by Django 5.1.4 on 2024-12-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='category_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('image2', models.ImageField(default='default.jpg', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('logo', models.ImageField(default='default.jpg', upload_to='')),
                ('instagram', models.CharField(max_length=220)),
                ('linkdin', models.CharField(max_length=220)),
                ('twiter', models.CharField(max_length=220)),
                ('facebook', models.CharField(max_length=220)),
                ('content_agent', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='blog.category_blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.users')),
                ('tags', models.ManyToManyField(to='blog.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.detail_blog')),
            ],
        ),
    ]
