# Generated by Django 5.1.4 on 2024-12-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category_blog',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
