# Generated by Django 5.1.4 on 2024-12-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_status_category_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category_blog',
            name='title',
            field=models.CharField(max_length=220),
        ),
        migrations.CreateModel(
            name='Detail_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('image2', models.ImageField(default='default.jpg', upload_to='')),
                ('user', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('logo', models.ImageField(default='default.jpg', upload_to='')),
                ('instagram', models.CharField(max_length=220)),
                ('linkdin', models.CharField(max_length=220)),
                ('twiter', models.CharField(max_length=220)),
                ('facebook', models.CharField(max_length=220)),
                ('content_agent', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='blog.category_blog')),
                ('tags', models.ManyToManyField(to='blog.tags')),
            ],
        ),
    ]
