# Generated by Django 5.1.4 on 2024-12-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specials',
            name='status',
        ),
    ]
