# Generated by Django 5.1.4 on 2024-12-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_remove_specials_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='about_user',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='categoty',
        ),
    ]
