# Generated by Django 5.1.4 on 2024-12-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_remove_portfolio_ability_remove_portfolio_about_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='about',
            name='service',
        ),
    ]
