# Generated by Django 5.1.4 on 2024-12-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_about_desc_remove_about_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
