# Generated by Django 5.1.4 on 2024-12-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_remove_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('context', models.CharField(max_length=250)),
                ('logo', models.ImageField(default='default.jpg', upload_to='root')),
                ('domain', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('stars', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root.stars')),
            ],
        ),
    ]
