# Generated by Django 5.1.4 on 2024-12-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_contactus'),
        ('root', '0007_alter_tester_context_alter_tester_domain_and_more'),
    ]

    operations = [
    ]
